Update to 1.18 release
comp500/BorderlessMining pull request #18
Opened 2021-11-30 21:27 UTC by vanjmali

Update Fabric dependencies and code for 1.18

2021-12-03 04:54 UTC, 8times9 commented
How can I compile this pull request for myself? It seems that this project is abandoned.

2021-12-03 22:12 UTC, vanjmali commented
I believe you just need to make sure to use Java 17.
If you are using IntelliJ IDEA you would need to set your project to use Java 17 by going to `File > Settings > Build, Execution, Deployment > Build Tools > Gradle` (or Gradle Settings) and set `Gradle JVM` to `17`.

That should be all, I think. It also requires to use of Gradle 7.2+ to support that Java version which should be done automatically.

Here's also compiled jar file of the mod (extract it):
[borderless-mining-1.1.0+1.18.jar.zip](https://github.com/comp500/BorderlessMining/files/7652622/borderless-mining-1.1.0%2B1.18.jar.zip)

2021-12-04 03:02 UTC, comp500 commented
> How can I compile this pull request for myself? It seems that this project is abandoned. Or would there be a way you could compile it for me and offer a download?

This project isn't abandoned! I'm just very busy with work and other projects, so I don't often have enough time to update them.

2021-12-04 04:21 UTC, comp500 requested changes
Looks great, thanks! Just noted a small issue to fix.

2021-12-04 04:21 UTC, comp500 commented on src/main/java/link/infra/borderlessmining/config/ConfigScreen.java
> +//		public List<? extends Selectable> selectableChildren() {
I assume this comment has no purpose, could you remove it?

2021-12-04 05:05 UTC, 8times9 commented
> This project isn't abandoned! I'm just very busy with work and other projects, so I don't often have enough time to update them.

So sorry didn’t mean any disrespect! Can certainly understand life being too busy.

2021-12-04 17:41 UTC, comp500 approved these changes

2021-12-04 17:45 UTC, merged

2021-12-04 17:56 UTC, vanjmali commented
I believe you should also update Github Workflow for 1.18 branch to use Java 17 when able to as it is not able to build it at the moment.

2021-12-04 17:58 UTC, comp500 commented
Already did https://github.com/comp500/BorderlessMining/commit/70af29256c45928b3ed20013b790c573706c7ccc :)