Sodium Support
comp500/BorderlessMining pull request #80
Opened 2023-08-07 19:47 UTC by NulledBird

Adds a page to Sodium's video settings that allows modifying of most (read below) settings in the Mod Menu config.

Due to the way sodium's options work, there are no things like input boxes, but rather things like sliders. For this reason, things like the choosing the monitor are not available in the settings, as that would require building a custom option, and Sodium's documentation on this are little to none (I worked off looking at other mods that have Sodium compatibility).

I thought about adding in the full screen resolution option in, but since that is a vanilla option, sodium could implement this in the future, and so I decided to hold off on adding it.

2023-08-07 19:52 UTC, Madis0 commented
Just to be clear, is this built with Sodium 0.4.10 or 0.5 in mind?

2023-08-08 16:22 UTC, NulledBird commented
@Madis0 it should work with any sodium version (as long as the sodium itself doesn't change its file structure or any apis)

However, Sodium won't do that because they know that many mods will have to make major code base changes

2023-08-08 16:51 UTC, Madis0 commented
Well, Sodium 0.5 just _did_ breaking changes, but perhaps not that many in the UI then.

2023-08-08 21:19 UTC, NulledBird commented
> Well, Sodium 0.5 just _did_ breaking changes, but perhaps not that many in the UI then.

Just checked, it seems that it works fine. Looking at the change log, it was just mostly rendering changes, and nothing to do with the gui.

2024-01-05 19:24 UTC, Crafter-Y requested changes
Some code-style change requests

2024-01-05 19:24 UTC, Crafter-Y commented on src/main/resources/borderlessmining.mixins.json
> +      "SodiumOptionsMixin"
Can you make this consistant with the spacing above?

2024-01-05 19:24 UTC, Crafter-Y commented on gradle.properties
> +    sodium_version=1.20-0.4.10
the spacing seems to be off here

2024-02-02 07:26 UTC, widegeon commented
how do i make this work?

2024-03-04 00:49 UTC, NulledBird commented
Use the updated one by @UltimatChamp

It's much better and works

2024-03-04 00:49 UTC, closed without merging